import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nooro TODO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen w-full bg-[#1A1A1A]">
          <nav className="absolute flex justify-center items-center h-60 w-full bg-[#0D0D0D] gap-2 z-0">
            {/* 
            <Image
              aria-hidden
              src="/logo-long.svg"
              alt="logo icon"
              width={22}
              height={36}
            />
            <h1 className="text-4xl font-black text-[#4EA8DE] leading-10">
              Todo
            </h1>
            <h1 className="text-4xl font-black text-purple-400 leading-10">
              App
            </h1> */}
            <Image
              aria-hidden
              src="/logo-long.svg"
              alt="logo icon"
              width={226}
              height={48}
            />
          </nav>
          <div className="pt-60 z-30 w-full">{children}</div>
        </div>
      </body>
    </html>
  );
}

// font-family: 'Inter';
